version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local